#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # 1 укажите явный маршрут к серверу eureka (serviceUrl)
#  instance:
#    preferIpAddress: true # 2 использовать IP адрес
#spring:
#  spring:
#    application:
#      name: config-client
#    config:
#      import: "optional:configserver:"
#    cloud:
#      config:
#        discovery:
#          enabled: true
#          service-id: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
spring:
  application:
    name: configclient
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server