server:
  port: 0
spring:
  application:
    name: CLIENT-SERVICE
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
feign:
  circuitbreaker:
    enabled: true
