#server:
#  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: book-service
    config:
      import: "optional:configserver:"
  profiles:
    active: native
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true
  management:
    tracing:
      sampling:
      probability: 2.0
  data:
  mongodb:
#    port: 27017
#    host: localhost
    database: mongodb
    username: admin
    password: admin
