#
#spring:
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/psyhotel/advanced_eureka
#          search-paths:
#            - "/{application}/{profile}"
#            - "/ms-config-properties/{application}/{profile}"
#  application:
#    name: config-server
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#server:
#  port: 8888

#\

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/psyhotel/advanced_eureka
          searchPaths:
#            - "/{application}/{profile}"
#            - "/ms-config-properties/{configclient}/{profile}"
            - "/configclient/{profile}"
#            - "/ms-config-properties/Users/tema/IdeaProjects/advanced_eureka_config/ms-config-properties/dev/{profile}"
#            - "/Users/tema/IdeaProjects/advanced_eureka_config/ms-config-properties/dev/{profile}"
#            - "/ms-config-properties/dev/{profile}"
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}