server:
  port: 8888
spring:
    profiles: git
    cloud:
      config:
        server:
          git:
            uri: https://github.com/Psyhotel
            search-paths:
              - "ms-config-properties/{application}/{profile}"
             // - "https://github.com/psyhotel/advanced_eureka.git"

  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}